name: Example Workflow

on:
 release:
    types: [published]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Secret
        run: echo "The secret value is ${{ secrets.PYPI_API_TOKEN }}"
